create table if not exists public.observatorio_downloads (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descricao text,
  categoria text,
  arquivo_url text not null,
  tipo_arquivo text,
  tamanho_bytes bigint,
  ordem integer not null default 0,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists observatorio_downloads_public_idx
  on public.observatorio_downloads(ativo, ordem, titulo);

alter table public.observatorio_downloads enable row level security;

drop policy if exists "Downloads ativos sao publicos" on public.observatorio_downloads;
create policy "Downloads ativos sao publicos"
  on public.observatorio_downloads
  for select
  to anon, authenticated
  using (ativo = true);

drop policy if exists "Administradores do Observatorio gerenciam downloads" on public.observatorio_downloads;
create policy "Administradores do Observatorio gerenciam downloads"
  on public.observatorio_downloads
  for all
  to authenticated
  using (
    exists (
      select 1 from public.papeis_usuario
      where user_id = auth.uid()
        and papel in ('administrador', 'observatorio_admin')
    )
  )
  with check (
    exists (
      select 1 from public.papeis_usuario
      where user_id = auth.uid()
        and papel in ('administrador', 'observatorio_admin')
    )
  );

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'observatorio-downloads',
  'observatorio-downloads',
  true,
  31457280,
  array[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'text/csv',
    'text/plain',
    'application/zip',
    'image/png',
    'image/jpeg',
    'image/webp'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Downloads publicos podem ser lidos" on storage.objects;
create policy "Downloads publicos podem ser lidos"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'observatorio-downloads');

drop policy if exists "Administradores do Observatorio fazem upload de downloads" on storage.objects;
create policy "Administradores do Observatorio fazem upload de downloads"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'observatorio-downloads'
    and exists (
      select 1 from public.papeis_usuario
      where user_id = auth.uid()
        and papel in ('administrador', 'observatorio_admin')
    )
  );

drop policy if exists "Administradores do Observatorio atualizam downloads" on storage.objects;
create policy "Administradores do Observatorio atualizam downloads"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'observatorio-downloads'
    and exists (
      select 1 from public.papeis_usuario
      where user_id = auth.uid()
        and papel in ('administrador', 'observatorio_admin')
    )
  )
  with check (
    bucket_id = 'observatorio-downloads'
    and exists (
      select 1 from public.papeis_usuario
      where user_id = auth.uid()
        and papel in ('administrador', 'observatorio_admin')
    )
  );

drop policy if exists "Administradores do Observatorio removem downloads" on storage.objects;
create policy "Administradores do Observatorio removem downloads"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'observatorio-downloads'
    and exists (
      select 1 from public.papeis_usuario
      where user_id = auth.uid()
        and papel in ('administrador', 'observatorio_admin')
    )
  );
